export const headingTypes = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']
export const textTypes = ['lead', 'default', 'small']
export const listTypes = ['ul', 'ol']
export const inputTypes = ['text', 'password', 'search', 'email']
export const alertTypes = ['polite', 'assertive']
export const alertPositions = ['top', 'right']
